package calcul;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class CalculProfile extends javax.swing.JFrame {
    double Densitate_Otel = 7.85;
    double Densitate_Aluminiu = 2.7;
    double Densitate_Bronz = 8.2;
    double Densitate_Cupru = 8.95;
    double PI = 3.1415;
    double rad_3 = 1.73205080;
    
    /**
     * Creates new form NewJFrame
     */
    public CalculProfile() {
        initComponents();
        ImageIcon logo=new ImageIcon(getClass().getClassLoader().getResource("2.png"));
        this.setIconImage(logo.getImage());
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbMaterial = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtxtDim1 = new javax.swing.JTextField();
        jbtnCalc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbtnReset = new javax.swing.JButton();
        jlblRezultat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtDim2 = new javax.swing.JTextField();
        jtxtDim4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jcmbProfil = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jtxtDim3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jbtnExit = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jMenuBar4 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator profile");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(610, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Materialul:");
        jLabel1.setToolTipText("");

        jcmbMaterial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcmbMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alege...", "Otel", "Aluminiu", "Bronz", "Cupru" }));
        jcmbMaterial.setToolTipText("Materialul din care este facut profilul!");
        jcmbMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbMaterialActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Diametru, S_hexagon, Latime:");

        jtxtDim1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtDim1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDim1ActionPerformed(evt);
            }
        });

        jbtnCalc.setBackground(new java.awt.Color(153, 255, 153));
        jbtnCalc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnCalc.setText("Calculează");
        jbtnCalc.setToolTipText("Calculeaza masa profilului  conform optiunilor alese mai sus");
        jbtnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCalcActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Calculator greutăți profile laminate");
        jLabel3.setToolTipText("Titlul programului!");

        jbtnReset.setBackground(new java.awt.Color(153, 204, 255));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.setToolTipText("Goleste casutele de mai sus");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jlblRezultat.setBackground(new java.awt.Color(255, 255, 255));
        jlblRezultat.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlblRezultat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlblRezultat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlblRezultat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("[mm]");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("[kg]");
        jLabel5.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Masa profilului:");

        jtxtDim2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtDim2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDim2ActionPerformed(evt);
            }
        });

        jtxtDim4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtDim4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDim4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDim4ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Inaltime:");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Lungimea:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("[mm]");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("[m]");
        jLabel11.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Profilul:");
        jLabel6.setToolTipText("");

        jcmbProfil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcmbProfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alege...", "Rotund", "Rectangular", "Hexagonal", "Țeavă", "Țeavă rectangulară" }));
        jcmbProfil.setToolTipText("Forma profilului!");
        jcmbProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbProfilActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Grosime:");

        jtxtDim3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtDim3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("[mm]");
        jLabel16.setToolTipText("");

        jLabel17.setToolTipText("Se completează fiecare câmp! Programul validează doar datele utile fiecărui caz în parte!");

        jbtnExit.setBackground(new java.awt.Color(255, 0, 0));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setToolTipText("Inchide programul");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(255, 0, 0));
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calcul/Info.png"))); // NOI18N
        b1.setToolTipText("Informatii");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(0, 255, 255));
        b2.setText("Ce este un profil");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b2)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(jbtnExit)
                            .addGap(28, 28, 28)
                            .addComponent(jbtnReset)
                            .addGap(39, 39, 39)
                            .addComponent(jbtnCalc))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jcmbMaterial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcmbProfil, 0, 202, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxtDim2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxtDim1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtxtDim3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jtxtDim4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel10)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(jLabel11))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcmbMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jcmbProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtDim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtxtDim2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtxtDim3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtxtDim4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jlblRezultat, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnCalc)
                            .addComponent(jbtnReset)
                            .addComponent(jbtnExit))
                        .addGap(47, 47, 47)
                        .addComponent(b2))))
        );

        setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jcmbProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbProfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbProfilActionPerformed

    private void jtxtDim4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDim4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDim4ActionPerformed

    private void jtxtDim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDim2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDim2ActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jlblRezultat.setText(null);
        jtxtDim1.setText(null);
        jtxtDim2.setText(null);
        jtxtDim3.setText (null);
        jtxtDim4.setText(null);
        jcmbMaterial.setSelectedIndex(0);
        jcmbProfil.setSelectedIndex(0);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCalcActionPerformed

        /* calculul maselor pt. materialul "Otel", in combinatie cu toate tipurile de profile din lista*/

        if(jcmbMaterial.getSelectedItem()!="Alege..."&&jcmbProfil.getSelectedItem().equals("Alege..."))
            JOptionPane.showMessageDialog(jPanel1,"Ai uitat să alegi profilul!");
        if(jcmbMaterial.getSelectedItem().equals("Alege...")&&jcmbProfil.getSelectedItem()!="Alege...")
            JOptionPane.showMessageDialog(jPanel1,"Ai uitat să alegi materialul!");
        if(jcmbMaterial.getSelectedItem().equals("Alege..."))
        {
            if(jcmbProfil.getSelectedItem().equals("Alege..."))
            {
               JOptionPane.showMessageDialog(jPanel1,"Ai uitat să alegi materialul!\n Ai uitat să alegi profilul!"); 
            }   
        }
        if (jcmbMaterial.getSelectedItem().equals("Otel"))
        {
            if (jcmbProfil.getSelectedItem().equals("Rotund"))
            {
                jtxtDim2.setText(null);
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim1 * PI/4 * Dim4 * Densitate_Otel/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Rectangular"))
            {
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim2 = Double.parseDouble(jtxtDim2.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim2 * Dim4 * Densitate_Otel/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Hexagonal"))
            {
                jtxtDim2.setText(null);
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim1 * rad_3/2 * Dim4 * Densitate_Otel/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Țeavă"))
            {
                jtxtDim2.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim3 = Double.parseDouble(jtxtDim3.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", PI * Dim3 * (Dim1 - Dim3) * Dim4 * Densitate_Otel/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Țeavă rectangulară"))
            {
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim2 = Double.parseDouble(jtxtDim2.getText());
                double Dim3 = Double.parseDouble(jtxtDim3.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", 2 * Dim3 * (Dim1 + Dim2 - 2 * Dim3) * Dim4 * Densitate_Otel/1000);
                jlblRezultat.setText(Valoare);
            }
        }

        /* calculul maselor pt. materialul "Aluminiu", in combinatie cu toate tipurile de profile din lista */

        if (jcmbMaterial.getSelectedItem().equals("Aluminiu"))
        {
            if (jcmbProfil.getSelectedItem().equals("Rotund"))
            {
                jtxtDim2.setText(null);
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim1 * PI/4 * Dim4 * Densitate_Aluminiu/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Rectangular"))
            {
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim2 = Double.parseDouble(jtxtDim2.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim2 * Dim4 * Densitate_Aluminiu/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Hexagonal"))
            {
                jtxtDim2.setText(null);
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim1 * rad_3/2 * Dim4 * Densitate_Aluminiu/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Țeavă"))
            {
                jtxtDim2.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim3 = Double.parseDouble(jtxtDim3.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", PI * Dim3 * (Dim1 - Dim3) * Dim4 * Densitate_Aluminiu/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Țeavă rectangulară"))
            {
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim2 = Double.parseDouble(jtxtDim2.getText());
                double Dim3 = Double.parseDouble(jtxtDim3.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", 2 * Dim3 * (Dim1 + Dim2 - 2 * Dim3) * Dim4 * Densitate_Aluminiu/1000);
                jlblRezultat.setText(Valoare);
            }
        }

        /* calculul maselor pt. materialul "Bronz", in combinatie cu toate tipurile de profile din lista */

        if (jcmbMaterial.getSelectedItem().equals("Bronz"))
        {
            if (jcmbProfil.getSelectedItem().equals("Rotund"))
            {
                jtxtDim2.setText(null);
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim1 * PI/4 * Dim4 * Densitate_Bronz/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Rectangular"))
            {
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim2 = Double.parseDouble(jtxtDim2.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim2 * Dim4 * Densitate_Bronz/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Hexagonal"))
            {
                jtxtDim2.setText(null);
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim1 * rad_3/2 * Dim4 * Densitate_Bronz/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Țeavă"))
            {
                jtxtDim2.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim3 = Double.parseDouble(jtxtDim3.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", PI * Dim3 * (Dim1 - Dim3) * Dim4 * Densitate_Bronz/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Țeavă rectangulară"))
            {
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim2 = Double.parseDouble(jtxtDim2.getText());
                double Dim3 = Double.parseDouble(jtxtDim3.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", 2 * Dim3 * (Dim1 + Dim2 - 2 * Dim3) * Dim4 * Densitate_Bronz/1000);
                jlblRezultat.setText(Valoare);
            }
        }

        /* calculul maselor pt. materialul "Cupru", in combinatie cu toate tipurile de profile din lista */

        if (jcmbMaterial.getSelectedItem().equals("Cupru"))
        {
            if (jcmbProfil.getSelectedItem().equals("Rotund"))
            {
                jtxtDim2.setText(null);
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim1 * PI/4 * Dim4 * Densitate_Cupru/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Rectangular"))
            {
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim2 = Double.parseDouble(jtxtDim2.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim2 * Dim4 * Densitate_Cupru/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Hexagonal"))
            {
                jtxtDim2.setText(null);
                jtxtDim3.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", Dim1 * Dim1 * rad_3/2 * Dim4 * Densitate_Cupru/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Țeavă"))
            {
                jtxtDim2.setText(null);
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim3 = Double.parseDouble(jtxtDim3.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", PI * Dim3 * (Dim1 - Dim3) * Dim4 * Densitate_Cupru/1000);
                jlblRezultat.setText(Valoare);
            }

            if (jcmbProfil.getSelectedItem().equals("Țeavă rectangulară"))
            {
                double Dim1 = Double.parseDouble(jtxtDim1.getText());
                double Dim2 = Double.parseDouble(jtxtDim2.getText());
                double Dim3 = Double.parseDouble(jtxtDim3.getText());
                double Dim4 = Double.parseDouble(jtxtDim4.getText());
                String Valoare = String.format("%.3f", 2 * Dim3 * (Dim1 + Dim2 - 2 * Dim3) * Dim4 * Densitate_Cupru/1000);
                jlblRezultat.setText(Valoare);
            }
        }

    }//GEN-LAST:event_jbtnCalcActionPerformed

    private void jtxtDim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDim1ActionPerformed

    private void jcmbMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbMaterialActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        b1.setBackground(Color.RED);
        JOptionPane.showMessageDialog(jPanel1,"Acest program calculeaza greutatea/masa unui profil in functie de caracteristicile acestuia.","Informații",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        JOptionPane.showMessageDialog(jPanel1,"Profilul este un dispozitiv sau ansamblu de piese folosit pentru a indica, într-un plan vertical, limitele până la care trebuie să se întindă o lucrare.","Ce este un profil?",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_b2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new CalculProfile().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCalc;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JComboBox<String> jcmbMaterial;
    private javax.swing.JComboBox<String> jcmbProfil;
    private javax.swing.JLabel jlblRezultat;
    private javax.swing.JTextField jtxtDim1;
    private javax.swing.JTextField jtxtDim2;
    private javax.swing.JTextField jtxtDim3;
    private javax.swing.JTextField jtxtDim4;
    // End of variables declaration//GEN-END:variables
}
